set serveroutput on
set verify off

CREATE TABLE T_CLYVO_VET(
id_vet number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
nm_vet VARCHAR(20) not null,
cpf_vet VARCHAR(14) not null,
crmv_vet VARCHAR(20) not null,
email VARCHAR(20) NOT NULL,
senha VARCHAR(20) NOT NULL
);

CREATE TABLE T_CLYVO_ENDERECO_CLINICA(
id_endereco_clinica number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
tipo VARCHAR(20) NOT NULL
);

CREATE TABLE T_CLYVO_CLINICA(
id_clinica number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
cnpj_clinica VARCHAR(20) not null,
nm_clinica VARCHAR(20) not null,
id_endereco_clinica number(2) not null,
CONSTRAINT fk_en_clinica FOREIGN KEY (id_endereco_clinica) REFERENCES T_CLYVO_ENDERECO_CLINICA(id_endereco_clinica)
);

CREATE TABLE T_CLYVO_TUTOR(
id_tutor number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
cpf_tutor VARCHAR(14) NOT NULL,
nm_tutor VARCHAR(20) NOT NULL,
nr_telefone_tutor VARCHAR(13)
);

CREATE TABLE T_CLYVO_ENDERECO_USUARIO(
id_endereco_usuario number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
tipo VARCHAR(20) NOT NULL
);

CREATE TABLE T_CLYVO_ANIMAL(
id_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
rg_animal VARCHAR(20),
nr_microchip_animal VARCHAR(20),
nm_animal VARCHAR(20) NOT NULL,
dt_nascimento_animal DATE NOT NULL,
peso_animal number(5,2) NOT NULL,
especie_animal VARCHAR(20) NOT NULL,
raca_animal VARCHAR(20) NOT NULL,
id_tutor number(2) NOT NULL,
id_endereco_usuario number(2) NOT NULL,
CONSTRAINT fk_an_tutor FOREIGN KEY (id_tutor) REFERENCES T_CLYVO_TUTOR(id_tutor),
CONSTRAINT fk_an_endereco FOREIGN KEY (id_endereco_usuario) REFERENCES T_CLYVO_ENDERECO_USUARIO(id_endereco_usuario)
);

CREATE TABLE T_CLYVO_CARTEIRAVACINAL(
id_carteiravacinal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nm_vacina VARCHAR(20) NOT NULL,
dt_vacinacao_prevista DATE,
dt_vacinacao_efetuada DATE,
st_vacinacao VARCHAR(20),
id_animal number(2) not null,
CONSTRAINT fk_an_carteiravacinal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_PRESCRICAO(
id_prescricao number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
medicamento_prescricao VARCHAR(20) NOT NULL,
nm_tutor_prescricao VARCHAR(20) NOT NULL,
nm_animal_prescricao VARCHAR(20) NOT NULL,
dt_emissao DATE NOT NULL,
dt_expiracao DATE NOT NULL
);


CREATE TABLE T_CLYVO_MEDICAMENTO(
id_medicamento number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
id_prescricao number(2) not null,
nm_medicamento VARCHAR(20) NOT NULL,
dosagem_medicamento VARCHAR(20) NOT NULL,
frequencia VARCHAR(10) NOT NULL,
qtd_dias number(2) NOT NULL,
CONSTRAINT fk_med_prescicao FOREIGN KEY (id_prescricao) REFERENCES T_CLYVO_PRESCRICAO(id_prescricao))


CREATE TABLE T_CLYVO_VET_CLINICA(
id_clinica_vet number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
id_vet number(2) not null,
id_clinica number(2) not null,
CONSTRAINT fk_vet FOREIGN KEY(id_vet) REFERENCES T_CLYVO_VET(id_vet),
CONSTRAINT fk_clinica FOREIGN KEY(id_clinica) REFERENCES T_CLYVO_CLINICA(id_clinica)
);

CREATE TABLE T_CLYVO_CONSULTA(
id_consulta number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
historico_cosnsulta VARCHAR(200) NOT NULL,
st_consulta VARCHAR(20) CHECK (st_consulta IN ('passada','execução','futura','cancelada')) NOT NULL,
dt_consulta DATE NOT NULL,
id_clinica_vet number(2)NOT NULL,
id_animal number(2) NOT NULL,
id_prescricao number(2) NOT NULL,
CONSTRAINT fk_con_vet_cl FOREIGN KEY (id_clinica_vet) REFERENCES T_CLYVO_VET_CLINICA(id_clinica_vet),
CONSTRAINT fk_con_animal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal),
CONSTRAINT fk_con_prescricao FOREIGN KEY (id_prescricao) REFERENCES T_CLYVO_PRESCRICAO(id_prescricao)
);

//Tabela log

CREATE TABLE logs(
id_log NUMBER(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nm_procedure VARCHAR(20),
nm_usuario VARCHAR(20),
dt_usuario DATE,
codigo_erro NUMBER(2),
mensagem_erro VARCHAR(200)
);
//PROCEDURE

//Vet
CREATE OR REPLACE PROCEDURE dados_vet(
    p_nm_vet VARCHAR2,
    p_cpf_vet VARCHAR2,
    p_crmv_vet VARCHAR2,
    p_email VARCHAR2,
    p_senha VARCHAR2
)
IS
BEGIN 
    INSERT INTO T_CLYVO_VET(
    nm_vet,
    cpf_vet, 
    crmv_vet, 
    email,
    senha
    )
    VALUES (p_nm_vet,
        p_cpf_vet,
        p_crmv_vet,
        p_email,
        p_senha);
    
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO lOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(NULL,
                'Dados_vet',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro no valor'
            );
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Errono_vet',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro no valor'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
             nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_vet',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
            
    END dados_vet;
    /
   
// endereco clinica
CREATE OR REPLACE PROCEDURE dados_endereco_clinica(
    p_pais VARCHAR2,
    p_estado VARCHAR2,
    p_cidade VARCHAR2,
    p_bairro VARCHAR2,
    p_logradouro_rua VARCHAR2,
    p_nr_rua VARCHAR2,
    p_completo VARCHAR2,
    p_cep VARCHAR2,
    p_tipo VARCHAR2
)
IS
BEGIN 
    INSERT INTO T_CLYVO_ENDERECO_CLINICA
    (
    pais,
    estado, 
    cidade, 
    bairro,
    logradouro_rua,
    nr_rua,
    completo,
    cep,
    tipo
    )
    VALUES (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_tipo
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Endereco_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'valor erro'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
             nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_en_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_endereco_clinica;
/

//clinica

CREATE OR REPLACE PROCEDURE dados_clinica(
    p_cnpj_clinica VARCHAR2,
    p_nm_clinica VARCHAR2,
    p_id_endereco_clinica NUMBER
)
IS
BEGIN 
    INSERT INTO T_CLYVO_CLINICA
    (cnpj_clinica,
    nm_clinica, 
    id_endereco_clinica)
    VALUES 
    (
        p_cnpj_clinica,
        p_nm_clinica,
        p_id_endereco_clinica
        );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'valor da clinica'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )VALUES (
            'dados_clinica',
            USER,
            SYSDATE,
            SQLCODE,
            SQLERRM
        );
END dados_clinica;
/

//Tutor Animal
CREATE OR REPLACE PROCEDURE dados_tutor(
    p_cpf_tutor VARCHAR2,
    p_nm_tutor VARCHAR2,
    p_nr_telefone_tutor VARCHAR2
)
IS
BEGIN 
    INSERT INTO T_CLYVO_TUTOR
    (cpf_tutor, nm_tutor, nr_telefone_tutor
    )
    VALUES (p_cpf_tutor, p_nm_tutor, p_nr_telefone_tutor
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_tutor',
                USER,
                SYSDATE,
                SQLCODE,
                'erro no valor'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_tutor',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_tutor;
/
//Endereco Usuario

CREATE OR REPLACE PROCEDURE dados_endereco_usuario(
    p_pais VARCHAR2,
    p_estado VARCHAR2,
    p_cidade VARCHAR2,
    p_bairro VARCHAR2,
    p_logradouro_rua VARCHAR2,
    p_nr_rua VARCHAR2,
    p_completo VARCHAR2,
    p_cep VARCHAR2,
    p_tipo VARCHAR2
)
IS
BEGIN 
    INSERT INTO T_CLYVO_ENDERECO_USUARIO
    (
    pais,
    estado, 
    cidade,
    bairro,
    logradouro_rua,
    nr_rua,
    completo,
    cep,
    tipo
    )
    VALUES (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_tipo
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO lOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_endereco_usuario',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro nos valores'
            );
         WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_tutor',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
        
END dados_endereco_usuario;
/

//Animal

CREATE OR REPLACE PROCEDURE dados_animal(
    p_rg_animal VARCHAR2,
    p_nr_microchip_animal VARCHAR2,
    p_nm_animal VARCHAR2,
    p_dt_nascimento_animal DATE,
    p_peso_animal NUMBER,
    p_especie_animal VARCHAR2,
    p_raca_animal VARCHAR2,
    p_id_tutor NUMBER,
    p_id_endereco_usuario NUMBER
)
IS
BEGIN 
    INSERT INTO T_CLYVO_ANIMAL
    (rg_animal, nr_microchip_animal, 
    nm_animal, dt_nascimento_animal, peso_animal,
    especie_animal, raca_animal, id_tutor,
    id_endereco_usuario)
    VALUES (
        p_rg_animal,
        p_nr_microchip_animal,
        p_nm_animal,
        p_dt_nascimento_animal,
        p_peso_animal,
        p_especie_animal,
        p_raca_animal,
        p_id_tutor,
        p_id_endereco_usuario
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(NULL,
                'Dados_Animais',
                USER,
                SYSDATE,
                SQLCODE,
                'valor animal'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_animal',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_animal;
/

//Carteira Vacinal
CREATE OR REPLACE PROCEDURE dados_carteiravacinal(
    p_nm_vacina VARCHAR2,
    p_dt_vacinacao_prevista DATE,
    p_dt_vacinacao_efetuada DATE,
    p_st_vacinacao VARCHAR2,
    p_id_animal NUMBER
)
IS
BEGIN 
    INSERT INTO T_CLYVO_CARTEIRAVACINAL
    (
    nm_vacina,
    dt_vacinacao_prevista,
    dt_vacinacao_efetuada,
    st_vacinacao,
    id_animal
    )
    VALUES (
        p_nm_vacina,
        p_dt_vacinacao_prevista,
        p_dt_vacinacao_efetuada,
        p_st_vacinacao,
        p_id_animal
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_cateiravacinal',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro nos valores'
            );
        when others then 
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
                
            ) VALUES (
            'DADOS_CARTEIRAVACINAL', 
            USER, 
            SYSDATE, 
            SQLCODE,
            SQLERRM);
            
END dados_carteiravacinal;
/

//Prescricao
CREATE OR REPLACE PROCEDURE dados_prescricao(
    p_medicamento_prescricao VARCHAR2,
    p_nm_tutor_prescricao VARCHAR2,
    p_nm_animal_prescricao VARCHAR2,
    p_dt_emissao DATE,
    p_dt_expiracao DATE
)
IS
BEGIN 
    INSERT INTO T_CLYVO_PRESCRICAO
    (
    medicamento_prescricao,
    nm_tutor_prescricao,
    nm_animal_prescricao,
    dt_emissao,
    dt_expiracao 
    )
    VALUES (
        p_medicamento_prescricao,
        p_nm_tutor_prescricao,
        p_nm_animal_prescricao,
        p_dt_emissao,
        p_dt_expiracao 
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Erro_prescricao',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro nos valores'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values (
            'dados_prescricao',
            USER,
            SYSDATE,
            SQLCODE,
            SQLERRM
        );
END dados_prescricao;
/

//Medicamento
CREATE OR REPLACE PROCEDURE dados_medicamento(
    p_id_prescricao NUMBER,
    p_nm_medicamento VARCHAR2,
    p_dosagem_medicamento VARCHAR2,
    p_frequencia VARCHAR2,
    p_qtd_dias NUMBER
)
IS
BEGIN 
    INSERT INTO T_CLYVO_MEDICAMENTO
    (
    id_prescricao,
    nm_medicamento,
    dosagem_medicamento,
    frequencia,
    qtd_dias 
    )
    VALUES (
        p_id_prescricao,
        p_nm_medicamento,
        p_dosagem_medicamento,
        p_frequencia,
        p_qtd_dias
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_medicamento',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro nos valores'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values (
            'dados_medicamento',
            USER,
            SYSDATE,
            SQLCODE,
            SQLERRM
        );
END dados_medicamento;
/
//Vet clinica

CREATE OR REPLACE PROCEDURE dados_vet_clinica(
    p_id_vet NUMBER,
    p_id_clinica NUMBER
)
IS
BEGIN 
    INSERT INTO T_CLYVO_VET_CLINICA
    (
    id_vet,
    id_clinica
    )
    VALUES (
        p_id_vet,
        p_id_clinica
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Erro na vet clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro nos valores'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )VALUES (
                'dados_vet_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_vet_clinica;
/

//Consulta
CREATE OR REPLACE PROCEDURE dados_consulta(
    p_historico_consulta VARCHAR2,
    p_st_consulta VARCHAR2,
    p_dt_consulta DATE,
    p_id_clinica_vet NUMBER,
    p_id_animal NUMBER,
    p_id_prescricao NUMBER
)
IS
BEGIN 
    INSERT INTO T_CLYVO_CONSULTA
    (
        historico_cosnsulta,
        st_consulta,
        dt_consulta,
        id_clinica_vet,
        id_animal,
        id_prescricao
    )
    VALUES (
        p_historico_consulta,
        p_st_consulta,
        p_dt_consulta,
        p_id_clinica_vet,
        p_id_animal,
        p_id_prescricao
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_consulta',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro de valor'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_usuario,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_consulta',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_consulta;
/

//entrada do usuario ao sistema 

DECLARE 
    CURSOR c_vet IS SELECT email, senha FROM T_CLYVO_VET;
    v_email VARCHAR(254) := '&email';
    v_senha VARCHAR(60) :='&senha';
    
    v_valido BOOLEAN := FALSE;
BEGIN
    FOR v_vet in v_c LOOP
        IF v_vet.email = v_email AND v_vet.senha = v_senha THEN
            v_valido := TRUE;
            EXIT;
        END IF;
    END LOOP;
    IF v_valido THEN
        dbms_output.put_line( 'Login executado' );
    ELSE
        dbms_output.put_line( 'Email ou senha incorrentos' );
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        INSERT INTO logs(
            nm_procedure,
            nm_usuario,
            dt_usuario,
            codigo_erro,
            mensagem_erro
        ) VALUES(
            'Erro no Login',
            USER,
            SYSDATE,
            SQLCODE,
            SQLERRM
        );
END;

//cadastrar a consulta - opcao se tem o animal no banco de dados e se nao tem e ai tem que criar



//buscar informação do pet

//buscar informacao do tutor










