set serveroutput on
set verify off

CREATE TABLE T_CLYVO_VET(
id_vet number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
nm_vet VARCHAR(20) not null,
cpf_vet VARCHAR(14) UNIQUE NOT NULL,
crmv_vet VARCHAR(20) UNIQUE NOT NULL,
email VARCHAR(20) NOT NULL UNIQUE,
senha VARCHAR(20) NOT NULL
);

CREATE TABLE T_CLYVO_CLINICA(
id_clinica number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
cnpj_clinica VARCHAR(20) unique not null,
nm_clinica VARCHAR(20) not null
);

CREATE TABLE T_CLYVO_ENDERECO_CLINICA(
id_endereco_clinica number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
id_clinica number(2),
CONSTRAINT fk_en_clinica FOREIGN KEY (id_clinica) REFERENCES T_CLYVO_CLINICA(id_clinica)

);

CREATE TABLE T_CLYVO_VET_CLINICA(
id_clinica_vet number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
id_vet number(2) not null,
id_clinica number(2) not null,
CONSTRAINT fk_vet FOREIGN KEY(id_vet) REFERENCES T_CLYVO_VET(id_vet),
CONSTRAINT fk_clinica FOREIGN KEY(id_clinica) REFERENCES T_CLYVO_CLINICA(id_clinica)
);

CREATE TABLE T_CLYVO_RESPONSAVEL(
id_responsavel number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
cpf_responsavel VARCHAR(20) UNIQUE NOT NULL,
nm_responsavel VARCHAR(20) NOT NULL,
nr_telefone_responsavel VARCHAR(13) NOT NULL
);

CREATE TABLE T_CLYVO_ENDERECO_RESPONSAVEL(
id_endereco_responsavel number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
id_responsavel number(2) NOT NULL,
CONSTRAINT fk_en_responsavel FOREIGN KEY(id_responsavel) REFERENCES T_CLYVO_RESPONSAVEL(id_responsavel)
);

CREATE TABLE T_CLYVO_ANIMAL(
id_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
rg_animal VARCHAR(20),
nr_microchip_animal VARCHAR(20),
nm_animal VARCHAR(20) NOT NULL,
dt_nascimento_animal DATE NOT NULL,
peso_animal number(5,2) NOT NULL,
especie_animal VARCHAR(20) NOT NULL,
raca_animal VARCHAR(20) NOT NULL,
id_responsavel number(2) NOT NULL,
CONSTRAINT fk_an_responsavel FOREIGN KEY (id_responsavel) REFERENCES T_CLYVO_RESPONSAVEL(id_responsavel)
);

CREATE TABLE T_CLYVO_ENDERECO_ANIMAL(
id_endereco_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
id_animal number(2) NOT NULL,
CONSTRAINT fk_en_animal FOREIGN KEY(id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_CARTEIRAVACINAL(
id_carteiravacinal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nm_vacina VARCHAR(20) NOT NULL,
dt_vacinacao_prevista DATE,
dt_vacinacao_efetuada DATE NOT NULL,
st_vacinacao VARCHAR(20) CHECK (st_vacinacao IN ('EFETUADA','PENDENTE','ATRASADA','CANCELADA')),
id_animal number(2) not null,
CONSTRAINT fk_an_carteiravacinal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_CONSULTA(
id_consulta number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
historico_consulta VARCHAR(200) NOT NULL,
st_consulta VARCHAR(20) CHECK (st_consulta IN ('passada','execução','futura','cancelada')) NOT NULL,
dt_consulta DATE NOT NULL,
id_vet number(2) NOT NULL,
id_animal number(2) NOT NULL,
CONSTRAINT fk_con_vet FOREIGN KEY (id_vet) REFERENCES T_CLYVO_VET(id_vet),
CONSTRAINT fk_con_animal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_PRESCRICAO(
id_prescricao number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
dt_emissao DATE NOT NULL,
dt_expiracao DATE NOT NULL,
id_consulta number(2) NOT NULL,
observacoes_gerais VARCHAR(255),
CONSTRAINT fk_prescricao FOREIGN KEY (id_consulta) REFERENCES T_CLYVO_CONSULTA(id_consulta)
);


CREATE TABLE T_CLYVO_MEDICAMENTO(
id_medicamento number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
id_prescricao number(2) not null,
nm_medicamento VARCHAR(20) NOT NULL,
dosagem_medicamento VARCHAR(20) NOT NULL,
frequencia VARCHAR(10) NOT NULL,
qtd_dias number(2) NOT NULL,
CONSTRAINT fk_med_prescicao FOREIGN KEY (id_prescricao) REFERENCES T_CLYVO_PRESCRICAO(id_prescricao)
);

--Tabela log

CREATE TABLE LOGS(
id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nm_procedure VARCHAR(100),
nm_usuario VARCHAR(50),
dt_ocorrencia DATE,
codigo_erro VARCHAR(50),
mensagem_erro VARCHAR(400)
);
--PROCEDURE

--Vet
CREATE OR REPLACE PROCEDURE dados_vet(
    p_nm_vet VARCHAR,
    p_cpf_vet VARCHAR,
    p_crmv_vet VARCHAR,
    p_email VARCHAR,
    p_senha VARCHAR
)
IS
BEGIN 
    INSERT INTO T_CLYVO_VET(
        nm_vet,
        cpf_vet, 
        crmv_vet, 
        email,
        senha
    )
    VALUES (
        p_nm_vet,
        p_cpf_vet,
        p_crmv_vet,
        p_email,
        p_senha
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO lOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Dados_vet',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em vet'
            );
        WHEN DUP_VAL_ON_INDEX THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Erro_vet',
                USER,
                SYSDATE,
                SQLCODE,
                'Dado já existente'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_vet',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );      
END dados_vet;


-- clinica

CREATE OR REPLACE PROCEDURE dados_clinica(
    p_cnpj_clinica VARCHAR,
    p_nm_clinica VARCHAR
)
IS
BEGIN 
    INSERT INTO T_CLYVO_CLINICA
    (
        cnpj_clinica,
        nm_clinica
    )
    VALUES 
        (
            p_cnpj_clinica,
            p_nm_clinica
        );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir dados clinica'
            );
        WHEN DUP_VAL_ON_INDEX  THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )values(
                'dados_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'CPNJ já existente.'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            VALUES (
                'dados_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_clinica;

   
-- endereco clinica
CREATE OR REPLACE PROCEDURE dados_endereco_clinica(
    p_pais VARCHAR,
    p_estado VARCHAR,
    p_cidade VARCHAR,
    p_bairro VARCHAR,
    p_logradouro_rua VARCHAR,
    p_nr_rua VARCHAR,
    p_completo VARCHAR,
    p_cep VARCHAR,
    p_id_clinica NUMBER
)
IS
v_id_clinica NUMBER :=0;
BEGIN 
    SELECT id_clinica INTO v_id_clinica FROM T_CLYVO_CLINICA
        WHERE id_clinica = p_id_clinica;

    INSERT INTO T_CLYVO_ENDERECO_CLINICA
    (
        pais,
        estado, 
        cidade, 
        bairro,
        logradouro_rua,
        nr_rua,
        completo,
        cep,
        id_clinica
    )
    VALUES 
    (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_id_clinica
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Endereco_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em endereço clinica'
            );
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_endereco_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'Id clinica não encontrado.'
        );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
             nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_en_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_endereco_clinica;

-- Vet clinica

CREATE OR REPLACE PROCEDURE dados_vet_clinica(
    p_id_vet NUMBER,
    p_id_clinica NUMBER)
IS
    v_id_vet number :=0;
    v_id_clinica number :=0;
BEGIN
    SELECT id_vet INTO v_id_vet FROM T_CLYVO_VET
        WHERE id_vet = p_id_vet;
        
    SELECT id_clinica INTO v_id_clinica FROM T_CLYVO_CLINICA
        WHERE id_clinica = p_id_clinica;

    INSERT INTO T_CLYVO_VET_CLINICA(
        id_vet,
        id_clinica)
    VALUES (
        p_id_vet,
        p_id_clinica
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Erro na vet clinica',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir vet clinica'
            );
         WHEN NO_DATA_FOUND THEN
            IF v_id_vet = 0 THEN
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro
                )
                values(
                    'dados_prescricao',
                    USER,
                    SYSDATE,
                    SQLCODE,
                    'Id de vet não encontrado na tabela de vet.'
                );
            ELSIF v_id_clinica = 0 THEN
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro
                )
                values(
                    'dados_prescricao',
                    USER,
                    SYSDATE,
                    SQLCODE,
                    'Id de clinica não encontrado na tabela de clinica.'
                );
            ELSE
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro
                )
                values(
                    'dados_prescricao',
                    USER,
                    SYSDATE,
                    SQLCODE,
                    'Id de Vet e Clinica não encontrado.'
                );
            END IF;
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )VALUES (
                'dados_vet_clinica',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_vet_clinica;

-- Responsavel

CREATE OR REPLACE PROCEDURE dados_responsavel(
    p_cpf_responsavel VARCHAR,
    p_nm_responsavel VARCHAR,
    p_nr_telefone_responsavel VARCHAR
)
IS
BEGIN 
    INSERT INTO T_CLYVO_RESPONSAVEL (
        cpf_responsavel, 
        nm_responsavel, 
        nr_telefone_responsavel
    )
    VALUES (
        p_cpf_responsavel,
        p_nm_responsavel,
        p_nr_telefone_responsavel
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_responsavel',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir responsavel'
            );
        WHEN DUP_VAL_ON_INDEX THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Erro_responsavel',
                USER,
                SYSDATE,
                SQLCODE,
                'CPF já existente presente na tabela responsavel'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_responsavel',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_responsavel;

-- Endereco Usuario

CREATE OR REPLACE PROCEDURE dados_endereco_responsavel(
    p_pais VARCHAR,
    p_estado VARCHAR,
    p_cidade VARCHAR,
    p_bairro VARCHAR,
    p_logradouro_rua VARCHAR,
    p_nr_rua VARCHAR,
    p_completo VARCHAR,
    p_cep VARCHAR,
    p_id_responsavel NUMBER
)
IS
v_id_responsavel NUMBER :=0;
BEGIN 
    
    SELECT id_responsavel INTO v_id_responsavel FROM T_CLYVO_RESPONSAVEL
        WHERE id_responsavel = p_id_responsavel;
    
    INSERT INTO T_CLYVO_ENDERECO_RESPONSAVEL (
        pais,
        estado, 
        cidade,
        bairro,
        logradouro_rua,
        nr_rua,
        completo,
        cep,
        id_responsavel
    )
    VALUES (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_id_responsavel
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO lOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_endereco_responsavel',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em endereço responsavel'
            );
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_endereco_responsavel',
                USER,
                SYSDATE,
                SQLCODE,
                'Id de responsavel não achado'
        );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_endereco_responsavel',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
        
END dados_endereco_responsavel;

-- Animal

CREATE OR REPLACE PROCEDURE dados_animal(
    p_rg_animal VARCHAR,
    p_nr_microchip_animal VARCHAR,
    p_nm_animal VARCHAR,
    p_dt_nascimento_animal DATE,
    p_peso_animal NUMBER,
    p_especie_animal VARCHAR,
    p_raca_animal VARCHAR,
    p_id_responsavel NUMBER
)
IS
v_id_responsavel NUMBER :=0;
BEGIN 

    SELECT id_responsavel INTO v_id_responsavel FROM T_CLYVO_RESPONSAVEL
        WHERE id_responsavel = p_id_responsavel;
    
    INSERT INTO T_CLYVO_ANIMAL(
        rg_animal,
        nr_microchip_animal, 
        nm_animal,
        dt_nascimento_animal,
        peso_animal,
        especie_animal,
        raca_animal,
        id_responsavel
        )
    VALUES (
        p_rg_animal,
        p_nr_microchip_animal,
        p_nm_animal,
        p_dt_nascimento_animal,
        p_peso_animal,
        p_especie_animal,
        p_raca_animal,
        p_id_responsavel
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values('Dados_Animais',
                USER,
                SYSDATE,
                SQLCODE,
                'valor animal');
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_animal',
                USER,
                SYSDATE,
                SQLCODE,
                'Id de responsavel não encontrado.'
        );
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_animal',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_animal;

-- Endereco Animal

CREATE OR REPLACE PROCEDURE dados_endereco_animal(
    p_pais VARCHAR,
    p_estado VARCHAR,
    p_cidade VARCHAR,
    p_bairro VARCHAR,
    p_logradouro_rua VARCHAR,
    p_nr_rua VARCHAR,
    p_completo VARCHAR,
    p_cep VARCHAR,
    p_id_animal NUMBER
)
IS
v_id_animal NUMBER :=0;
BEGIN 

    SELECT id_animal INTO v_id_animal FROM T_CLYVO_ANIMAL
        WHERE id_animal = p_id_animal;

    INSERT INTO T_CLYVO_ENDERECO_ANIMAL
    (
        pais,
        estado, 
        cidade,
        bairro,
        logradouro_rua,
        nr_rua,
        completo,
        cep,
        id_animal
    )
    VALUES (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_id_animal
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO lOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_endereco_animal',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir endereço animal.'
            );
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_endereco_animal',
                USER,
                SYSDATE,
                SQLCODE,
                'Id animal não encontrado na tabela'
            );
         WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_endereco_animal',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_endereco_animal;

-- Carteira Vacinal

CREATE OR REPLACE PROCEDURE dados_carteiravacinal(
    p_nm_vacina VARCHAR,
    p_dt_vacinacao_prevista DATE,
    p_dt_vacinacao_efetuada DATE,
    p_st_vacinacao VARCHAR,
    p_id_animal NUMBER
)
IS
v_id_animal NUMBER :=0;
BEGIN 

    SELECT id_animal INTO v_id_animal FROM T_CLYVO_ANIMAL
        WHERE id_animal = p_id_animal;
    
    INSERT INTO T_CLYVO_CARTEIRAVACINAL(
        nm_vacina,
        dt_vacinacao_prevista,
        dt_vacinacao_efetuada,
        st_vacinacao,
        id_animal
    )VALUES (
        p_nm_vacina,
        p_dt_vacinacao_prevista,
        p_dt_vacinacao_efetuada,
        p_st_vacinacao,
        p_id_animal
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_cateiravacinal',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em carteira vacinal'
            );
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_carteiravacinal',
                USER,
                SYSDATE,
                SQLCODE,
                'Id de animal não achado'
            );
        when others then 
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
                
            ) VALUES (
            'DADOS_CARTEIRAVACINAL', 
            USER, 
            SYSDATE, 
            SQLCODE,
            SQLERRM); 
END dados_carteiravacinal;

-- Consulta
CREATE OR REPLACE PROCEDURE dados_consulta(
    p_historico_consulta VARCHAR,
    p_st_consulta VARCHAR,
    p_dt_consulta DATE,
    p_id_vet NUMBER,
    p_id_animal NUMBER
)
IS
    v_id_vet NUMBER :=0;
    v_id_animal NUMBER :=0;
BEGIN
    SELECT id_vet INTO v_id_vet FROM T_CLYVO_VET
        WHERE id_vet = p_id_vet;
        
    SELECT id_animal INTO v_id_animal FROM T_CLYVO_ANIMAL
        WHERE id_animal = p_id_animal;
        
        INSERT INTO T_CLYVO_CONSULTA(
            historico_consulta,
            st_consulta,
            dt_consulta,
            id_vet,
            id_animal
        )VALUES (
            p_historico_consulta,
            p_st_consulta,
            p_dt_consulta,
            p_id_vet,
            p_id_animal
        );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_consulta',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em consulta'
            );
        WHEN NO_DATA_FOUND THEN
            IF v_id_vet = 0 THEN
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro
                )
                values(
                    'dados_prescricao',
                    USER,
                    SYSDATE,
                    SQLCODE,
                    'Id de Vet não encontrado'
                );
            ELSIF v_id_animal = 0 THEN
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro
                )
                values(
                    'dados_prescricao',
                    USER,
                    SYSDATE,
                    SQLCODE,
                    'Id de Animal não encontrado'
                );
            ELSE
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro
                )
                values(
                    'dados_prescricao',
                    USER,
                    SYSDATE,
                    SQLCODE,
                    'Id de animal e de vet não encontrado'
                );
            END IF;
        WHEN OTHERS THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            ) VALUES (
                'dados_consulta',
                USER,
                SYSDATE,
                SQLCODE,
                SQLERRM
            );
END dados_consulta;

-- Prescricao

CREATE OR REPLACE PROCEDURE dados_prescricao(
    p_dt_emissao DATE,
    p_dt_expiracao DATE,
    p_id_consulta NUMBER,
    p_observacoes_gerais VARCHAR
)
IS
v_id_consulta NUMBER := 0;
BEGIN 
    SELECT id_consulta INTO v_id_consulta FROM T_CLYVO_CONSULTA
        WHERE id_consulta = p_id_consulta;

    INSERT INTO T_CLYVO_PRESCRICAO(
        dt_emissao,
        dt_expiracao,
        id_consulta,
        observacoes_gerais
    )
    VALUES (
        p_dt_emissao,
        p_dt_expiracao,
        p_id_consulta,
        p_observacoes_gerais
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'Erro_prescricao',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em prescrição'
            );
         WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_prescricao',
                USER,
                SYSDATE,
                SQLCODE,
                'Id de id consulta não achado'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values (
            'dados_prescricao',
            USER,
            SYSDATE,
            SQLCODE,
            SQLERRM
        );
END dados_prescricao;

-- Medicamento

CREATE OR REPLACE PROCEDURE dados_medicamento(
    p_id_prescricao NUMBER,
    p_nm_medicamento VARCHAR,
    p_dosagem_medicamento VARCHAR,
    p_frequencia VARCHAR,
    p_qtd_dias NUMBER
)
IS
v_id_prescricao NUMBER :=0;
BEGIN 
    SELECT id_prescricao INTO v_id_prescricao FROM T_CLYVO_PRESCRICAO
        WHERE id_prescricao = p_id_prescricao;
        
    INSERT INTO T_CLYVO_MEDICAMENTO(
        id_prescricao,
        nm_medicamento,
        dosagem_medicamento,
        frequencia,
        qtd_dias 
    )
    VALUES (
        p_id_prescricao,
        p_nm_medicamento,
        p_dosagem_medicamento,
        p_frequencia,
        p_qtd_dias
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_medicamento',
                USER,
                SYSDATE,
                SQLCODE,
                'Erro em inserir em medicamento'
            );
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values(
                'dados_medicamento',
                USER,
                SYSDATE,
                SQLCODE,
                'Id de prescrição não encontrado na tabela.'
            );
        WHEN OTHERS THEN
            INSERT INTO LOGS (
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro
            )
            values (
            'dados_medicamento',
            USER,
            SYSDATE,
            SQLCODE,
            SQLERRM
        );
END dados_medicamento;

-- Inserir dados

--Vet
BEGIN 
    dados_vet(
    'Antonio',
    '12345678909',
    '12345-V',
    'antoniosantos@gmail.com',
    '12345'
    );
    COMMIT;
END;

BEGIN 
    dados_vet(
    'Ana',
    '17315657009',
    '54321-V',
    'anaMaria@gmail.com',
    '54321'
    );
    COMMIT;
END;

--clinica
BEGIN 
    dados_clinica(
    '1111111111111',
    'Saude pet'
    );
    COMMIT;
END;

BEGIN 
    dados_clinica(
    '222222222222',
    'Love'
    );
    COMMIT;
END;

--endereco_clinica
BEGIN 
    dados_endereco_clinica(
        'Brasil',
        'São Paulo',
        'São Paulo',
        'Lapa',
        '234',
        'Dom Mauro',
        '14253078',
        1
    );
    COMMIT;
END;
    
BEGIN 
    dados_endereco_clinica(
        'Brasil',
        'São Paulo',
        'Guarulhos',
        'Centro',
        '234',
        'Dona maria',
        '14253079',
        2
    );
    COMMIT;
END;

-- vet clinica
BEGIN 
     dados_vet_clinica(
        1,
        1
     );
     COMMIT;
END;

BEGIN 
     dados_vet_clinica(
        2,
        2
     );
     COMMIT;
END;

-- responsavel

BEGIN 
    dados_responsavel(
    '45812579024',
    'Jaci',
    '1134567890'
    );
    COMMIT;
END;

BEGIN 
    dados_responsavel(
    '54823687074',
    'Felipe',
    '11987456123'
    );
    COMMIT;
END;

-- Endereco responsavel
BEGIN
    dados_endereco_responsavel(
        'Brasil',
        'São Paulo',
        'São Paulo',
        'Lapa',
        'Dom jose',
        '123',
        '399',
        '01310200',
        1
    );
    COMMIT;
END;

BEGIN
    dados_endereco_responsavel(
        'Brasil',
        'São Paulo',
        'Guarulhos',
        'Vila Augusta',
        'Costa leste',
        '456',
        '499',
        '02540450',
        2
    );
    COMMIT;
END;
-- Animal

BEGIN
    dados_animal(
        NULL,
        '5482',
        'Athur',
        '2024-04-20',
        60.5,
        'cachorro',
        'golden retriever',
        1
    );
    COMMIT;
END;

BEGIN
    dados_animal(
        '54842785',
        '1230',
        'Mimosa',
        '2025-02-19',
        400,
        'vaca',
        'Angus',
        2
    );
    COMMIT;
END;

-- endereco animal

BEGIN 
    dados_endereco_animal(
        'Brasil',
        'São Paulo',
        'São Paulo',
        'Lapa',
        'Dom jose',
        '123',
        '399',
        '01310200',
        1
    );
    COMMIT;
END;

BEGIN 
    dados_endereco_animal(
        'Brasil',
        'São Paulo',
        'Presidente Prudente',
        'Rancharia',
        'rua dom santos',
        '789',
        '200',
        '01310222',
        2
    );
    COMMIT;
END;

-- Carteira Vacinal

BEGIN
    dados_carteiravacinal(
        'raiva',
        NULL,
        '2025-02-18',
        'EFETUADA',
        1
    );
    COMMIT;
END;

BEGIN
    dados_carteiravacinal(
        'Brucelose',
        '2026-11-24',
        '2025-08-30',
        'PENDENTE',
        2
    );
    COMMIT;
END;

--CONSULTA

BEGIN  
    dados_consulta(
        'O paciente está com uma frequencia grande de dor de coluna',
        'passada',
        '2026-05-13',
        1,
        1
    );
    COMMIT;
END;

BEGIN  
    dados_consulta(
        'O paciente está com sobpeso',
        'execução',
        '2026-10-13',
        2,
        2
    );
    COMMIT;
END;

-- prescricao

BEGIN
    dados_prescricao(
        '2026-05-13',
        '2027-05-13',
        1,
        'Paciente precisa tomar remedio a dor e ir encaminhamento imediato para especialistas'
    );
    COMMIT;
END;

-- Medicamento

BEGIN 
    dados_medicamento(
        1,
        'Carprofeno',
        '500mg por 7 dia',
        '1 por dia',
        7
    );
    COMMIT;
END;

-- entrada do usuario ao sistema 
-- cadastrar a consulta - opcao se tem o animal no banco de dados e se nao tem e ai tem que criar



-- buscar informação do pet

-- buscar informacao do dados_endereco_responsavel










