set serveroutput on
set verify off


-- DROP de tabelas (ordem inversa para respeitar as foreign keys)
DROP TABLE T_CLYVO_MEDICAMENTO CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_PRESCRICAO CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_CONSULTA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_CARTEIRAVACINAL CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_ENDERECO_ANIMAL CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_ANIMAL CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_ENDERECO_RESPONSAVEL CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_RESPONSAVEL CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_VET_CLINICA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_ENDERECO_CLINICA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_CLINICA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CLYVO_VET CASCADE CONSTRAINTS PURGE;
DROP TABLE LOGS CASCADE CONSTRAINTS PURGE;    

CREATE TABLE T_CLYVO_VET(
id_vet number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
nm_vet VARCHAR(20) not null,
cpf_vet VARCHAR(14) UNIQUE NOT NULL,
crmv_vet VARCHAR(20) UNIQUE NOT NULL,
email VARCHAR(20) NOT NULL UNIQUE,
senha VARCHAR(20) NOT NULL
);

CREATE TABLE T_CLYVO_CLINICA(
id_clinica number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
cnpj_clinica VARCHAR(20) unique not null,
nm_clinica VARCHAR(20) not null
);

CREATE TABLE T_CLYVO_ENDERECO_CLINICA(
id_endereco_clinica number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
id_clinica number(2),
CONSTRAINT fk_en_clinica FOREIGN KEY (id_clinica) REFERENCES T_CLYVO_CLINICA(id_clinica)
);

CREATE TABLE T_CLYVO_VET_CLINICA(
id_clinica_vet number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
id_vet number(2) not null,
id_clinica number(2) not null,
CONSTRAINT fk_vet FOREIGN KEY(id_vet) REFERENCES T_CLYVO_VET(id_vet),
CONSTRAINT fk_clinica FOREIGN KEY(id_clinica) REFERENCES T_CLYVO_CLINICA(id_clinica)
);

CREATE TABLE T_CLYVO_TUTOR(
id_tutor number(2) GENERATED BY DEFAULT AS IDENTITY primary key not null,
cpf_tutor VARCHAR(20) UNIQUE NOT NULL,
nm_tutor VARCHAR(20) NOT NULL,
nr_telefone_tutor VARCHAR(13) NOT NULL
);

CREATE TABLE T_CLYVO_ENDERECO_TUTOR(
id_endereco_tutor number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
id_tutor number(2) NOT NULL,
CONSTRAINT fk_en_tutor FOREIGN KEY(id_tutor) REFERENCES T_CLYVO_tutor(id_tutor)
);

CREATE TABLE T_CLYVO_ANIMAL(
id_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
rg_animal VARCHAR(20),
nr_microchip_animal VARCHAR(20),
nm_animal VARCHAR(20) NOT NULL,
dt_nascimento_animal DATE NOT NULL,
peso_animal number(5,2) NOT NULL,
especie_animal VARCHAR(20) NOT NULL,
raca_animal VARCHAR(20) NOT NULL,
id_tutor number(2) NOT NULL,
CONSTRAINT fk_an_tutor FOREIGN KEY (id_tutor) REFERENCES T_CLYVO_TUTOR(id_tutor)
);

CREATE TABLE T_CLYVO_ENDERECO_ANIMAL(
id_endereco_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pais VARCHAR(20) NOT NULL,
estado VARCHAR(20) NOT NULL,
cidade VARCHAR(20) NOT NULL,
bairro VARCHAR(20) NOT NULL,
logradouro_rua VARCHAR(20) NOT NULL,
nr_rua VARCHAR(20) NOT NULL,
completo VARCHAR(20) NOT NULL,
cep VARCHAR(9) NOT NULL,
id_animal number(2) NOT NULL,
CONSTRAINT fk_en_animal FOREIGN KEY(id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_CARTEIRAVACINAL(
id_carteiravacinal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nm_vacina VARCHAR(20) NOT NULL,
dt_vacinacao_prevista DATE,
dt_vacinacao_efetuada DATE NOT NULL,
st_vacinacao VARCHAR(20) CHECK (st_vacinacao IN ('EFETUADA','PENDENTE','ATRASADA','CANCELADA')),
id_animal number(2) not null,
CONSTRAINT fk_an_carteiravacinal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_CONSULTA(
id_consulta number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
historico_consulta VARCHAR(200) NOT NULL,
st_consulta VARCHAR(20) CHECK (st_consulta IN ('passada','execução','futura','cancelada')) NOT NULL,
dt_consulta DATE NOT NULL,
id_vet number(2) NOT NULL,
id_animal number(2) NOT NULL,
CONSTRAINT fk_con_vet FOREIGN KEY (id_vet) REFERENCES T_CLYVO_VET(id_vet),
CONSTRAINT fk_con_animal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_PRESCRICAO(
id_prescricao number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
dt_emissao DATE NOT NULL,
dt_expiracao DATE NOT NULL,
id_consulta number(2) NOT NULL,
observacoes_gerais VARCHAR(255),
CONSTRAINT fk_prescricao FOREIGN KEY (id_consulta) REFERENCES T_CLYVO_CONSULTA(id_consulta)
);


CREATE TABLE T_CLYVO_MEDICAMENTO(
id_medicamento number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
id_prescricao number(2) not null,
nm_medicamento VARCHAR(20) NOT NULL,
dosagem_medicamento VARCHAR(20) NOT NULL,
frequencia VARCHAR(10) NOT NULL,
qtd_dias number(2) NOT NULL,
CONSTRAINT fk_med_prescicao FOREIGN KEY (id_prescricao) REFERENCES T_CLYVO_PRESCRICAO(id_prescricao)
);

--Tabela log

CREATE TABLE LOGS(
id_log NUMBER(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nm_procedure VARCHAR(100),
nm_usuario VARCHAR(50),
dt_ocorrencia DATE,
codigo_erro VARCHAR(50),
mensagem_erro VARCHAR(400)
);
--PROCEDURE

--Vet
CREATE OR REPLACE PROCEDURE dados_vet(
    p_nm_vet VARCHAR,
    p_cpf_vet VARCHAR,
    p_crmv_vet VARCHAR,
    p_email VARCHAR,
    p_senha VARCHAR
)
IS
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    INSERT INTO T_CLYVO_VET(
        nm_vet,
        cpf_vet,
        crmv_vet,
        email,
        senha
    )
    VALUES (
        p_nm_vet,
        p_cpf_vet,
        p_crmv_vet,
        p_email,
        p_senha
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )
            VALUES(
                'dados_vet', 
                USER, 
                SYSDATE, 
                v_codigo_erro, 
                v_mensagem_erro
            ); 
            dbms_output.put_line(v_mensagem_erro);
        WHEN DUP_VAL_ON_INDEX THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )
            VALUES(
                'dados_vet',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_vet',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_vet;

-- clinica

CREATE OR REPLACE PROCEDURE dados_clinica(
    p_cnpj_clinica VARCHAR,
    p_nm_clinica VARCHAR
)
IS
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    INSERT INTO T_CLYVO_CLINICA(
        cnpj_clinica,
        nm_clinica
    )VALUES (
            p_cnpj_clinica,
            p_nm_clinica
        );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )
            VALUES(
                'dados_clinica', 
                USER, 
                SYSDATE, 
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN DUP_VAL_ON_INDEX THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )
            VALUES(
                'dados_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_clinica;
   
-- endereco clinica
CREATE OR REPLACE PROCEDURE dados_endereco_clinica(
    p_pais VARCHAR,
    p_estado VARCHAR,
    p_cidade VARCHAR,
    p_bairro VARCHAR,
    p_logradouro_rua VARCHAR,
    p_nr_rua VARCHAR,
    p_completo VARCHAR,
    p_cep VARCHAR,
    p_id_clinica NUMBER
)
IS
    v_id_clinica NUMBER := 0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    SELECT id_clinica INTO v_id_clinica FROM T_CLYVO_CLINICA
        WHERE id_clinica = p_id_clinica;

    INSERT INTO T_CLYVO_ENDERECO_CLINICA
    (
        pais,
        estado, 
        cidade, 
        bairro,
        logradouro_rua,
        nr_rua,
        completo,
        cep,
        id_clinica
    )
    VALUES 
    (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_id_clinica
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_en_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_en_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line('Id clinica não encontrado');
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_en_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_endereco_clinica;

-- Vet clinica

CREATE OR REPLACE PROCEDURE dados_vet_clinica(
    p_id_vet NUMBER,
    p_id_clinica NUMBER)
IS
    v_id_vet number :=0;
    v_id_clinica number :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN
    SELECT id_vet INTO v_id_vet FROM T_CLYVO_VET
        WHERE id_vet = p_id_vet;
        
    SELECT id_clinica INTO v_id_clinica FROM T_CLYVO_CLINICA
        WHERE id_clinica = p_id_clinica;

    INSERT INTO T_CLYVO_VET_CLINICA(
        id_vet,
        id_clinica)
    VALUES (
        p_id_vet,
        p_id_clinica
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_vet_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
         WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            IF v_id_vet = 0 THEN
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro 
                )VALUES (
                    'dados_vet_clinica',
                    USER,
                    SYSDATE,
                    v_codigo_erro, 
                    v_mensagem_erro
                );
                dbms_output.put_line('Id vet não encontrado');
            ELSIF v_id_clinica = 0 THEN
               INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro 
                )VALUES (
                    'dados_vet_clinica',
                    USER,
                    SYSDATE,
                    v_codigo_erro, 
                    v_mensagem_erro
                );
                dbms_output.put_line('Id clinica não encontrado');
            ELSE
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro 
                )VALUES (
                    'dados_vet_clinica',
                    USER,
                    SYSDATE,
                    v_codigo_erro, 
                    v_mensagem_erro
                );
                dbms_output.put_line('Id clinica e vet não encontrado');
            END IF;
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_vet_clinica',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_vet_clinica;

-- Tutor

CREATE OR REPLACE PROCEDURE dados_tutor(
    p_cpf_tutor VARCHAR,
    p_nm_tutor VARCHAR,
    p_nr_telefone_tutor VARCHAR
)
IS
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    INSERT INTO T_CLYVO_TUTOR (
        cpf_tutor, 
        nm_tutor, 
        nr_telefone_tutor
    )
    VALUES (
        p_cpf_tutor,
        p_nm_tutor,
        p_nr_telefone_tutor
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);

        WHEN DUP_VAL_ON_INDEX THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_tutor;

-- Endereco Usuario

CREATE OR REPLACE PROCEDURE dados_endereco_tutor(
    p_pais VARCHAR,
    p_estado VARCHAR,
    p_cidade VARCHAR,
    p_bairro VARCHAR,
    p_logradouro_rua VARCHAR,
    p_nr_rua VARCHAR,
    p_completo VARCHAR,
    p_cep VARCHAR,
    p_id_tutor NUMBER
)
IS
    v_id_tutor NUMBER :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    SELECT id_tutor INTO v_id_tutor FROM T_CLYVO_TUTOR
        WHERE id_tutor = p_id_tutor;
    
    INSERT INTO T_CLYVO_ENDERECO_TUTOR (
        pais,
        estado, 
        cidade,
        bairro,
        logradouro_rua,
        nr_rua,
        completo,
        cep,
        id_tutor
    )
    VALUES (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_id_tutor
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line('Id tutor não encontrado');
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_endereco_tutor;

-- Animal

CREATE OR REPLACE PROCEDURE dados_animal(
    p_rg_animal VARCHAR,
    p_nr_microchip_animal VARCHAR,
    p_nm_animal VARCHAR,
    p_dt_nascimento_animal DATE,
    p_peso_animal NUMBER,
    p_especie_animal VARCHAR,
    p_raca_animal VARCHAR,
    p_id_tutor NUMBER
)
IS
    v_id_tutor NUMBER :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    SELECT id_tutor INTO v_id_tutor FROM T_CLYVO_TUTOR
        WHERE id_tutor = p_id_tutor;
    INSERT INTO T_CLYVO_ANIMAL(
        rg_animal,
        nr_microchip_animal, 
        nm_animal,
        dt_nascimento_animal,
        peso_animal,
        especie_animal,
        raca_animal,
        id_tutor
        )
    VALUES (
        p_rg_animal,
        p_nr_microchip_animal,
        p_nm_animal,
        p_dt_nascimento_animal,
        p_peso_animal,
        p_especie_animal,
        p_raca_animal,
        p_id_tutor
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_tutor',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line('Id tutor não encontrado');
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_animal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_animal;

-- Endereco Animal

CREATE OR REPLACE PROCEDURE dados_endereco_animal(
    p_pais VARCHAR,
    p_estado VARCHAR,
    p_cidade VARCHAR,
    p_bairro VARCHAR,
    p_logradouro_rua VARCHAR,
    p_nr_rua VARCHAR,
    p_completo VARCHAR,
    p_cep VARCHAR,
    p_id_animal NUMBER
)
IS
    v_id_animal NUMBER :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 

    SELECT id_animal INTO v_id_animal FROM T_CLYVO_ANIMAL
        WHERE id_animal = p_id_animal;

    INSERT INTO T_CLYVO_ENDERECO_ANIMAL
    (
        pais,
        estado, 
        cidade,
        bairro,
        logradouro_rua,
        nr_rua,
        completo,
        cep,
        id_animal
    )
    VALUES (
        p_pais,
        p_estado,
        p_cidade,
        p_bairro,
        p_logradouro_rua,
        p_nr_rua,
        p_completo,
        p_cep,
        p_id_animal
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_animal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_animal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
         WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_endereco_animal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_endereco_animal;

-- Carteira Vacinal

CREATE OR REPLACE PROCEDURE dados_carteiravacinal(
    p_nm_vacina VARCHAR,
    p_dt_vacinacao_prevista DATE,
    p_dt_vacinacao_efetuada DATE,
    p_st_vacinacao VARCHAR,
    p_id_animal NUMBER
)
IS
    v_id_animal NUMBER :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 

    SELECT id_animal INTO v_id_animal FROM T_CLYVO_ANIMAL
        WHERE id_animal = p_id_animal;
    
    INSERT INTO T_CLYVO_CARTEIRAVACINAL(
        nm_vacina,
        dt_vacinacao_prevista,
        dt_vacinacao_efetuada,
        st_vacinacao,
        id_animal
    )VALUES (
        p_nm_vacina,
        p_dt_vacinacao_prevista,
        p_dt_vacinacao_efetuada,
        p_st_vacinacao,
        p_id_animal
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_carteiravacinal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
        WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_carteiravacinal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line('Id animal não encontrado');
        when others then 
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_carteiravacinal',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_carteiravacinal;

-- Consulta
CREATE OR REPLACE PROCEDURE dados_consulta(
    p_historico_consulta VARCHAR,
    p_st_consulta VARCHAR,
    p_dt_consulta DATE,
    p_id_vet NUMBER,
    p_id_animal NUMBER
)
IS
    v_id_vet NUMBER :=0;
    v_id_animal NUMBER :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN
    SELECT id_vet INTO v_id_vet FROM T_CLYVO_VET
        WHERE id_vet = p_id_vet;
        
    SELECT id_animal INTO v_id_animal FROM T_CLYVO_ANIMAL
        WHERE id_animal = p_id_animal;
        
        INSERT INTO T_CLYVO_CONSULTA(
            historico_consulta,
            st_consulta,
            dt_consulta,
            id_vet,
            id_animal
        )VALUES (
            p_historico_consulta,
            p_st_consulta,
            p_dt_consulta,
            p_id_vet,
            p_id_animal
        );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_consulta',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN NO_DATA_FOUND THEN
            IF v_id_vet = 0 THEN
                v_codigo_erro := TO_CHAR(SQLCODE);
                v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro 
                )VALUES (
                    'dados_consulta',
                    USER,
                    SYSDATE,
                    v_codigo_erro, 
                    v_mensagem_erro
                );
                dbms_output.put_line('Id vet não encontrado');
            ELSIF v_id_animal = 0 THEN
                v_codigo_erro := TO_CHAR(SQLCODE);
                v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro 
                )VALUES (
                    'dados_consulta',
                    USER,
                    SYSDATE,
                    v_codigo_erro, 
                    v_mensagem_erro
                );
                dbms_output.put_line('Id animal não encontrado');
            ELSE
                v_codigo_erro := TO_CHAR(SQLCODE);
                v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
                INSERT INTO LOGS(
                    nm_procedure,
                    nm_usuario,
                    dt_ocorrencia,
                    codigo_erro,
                    mensagem_erro 
                )VALUES (
                    'dados_consulta',
                    USER,
                    SYSDATE,
                    v_codigo_erro, 
                    v_mensagem_erro
                );
                dbms_output.put_line('Id vet e animal não encontrado');
            END IF;
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_consulta',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_consulta;

-- Prescricao

CREATE OR REPLACE PROCEDURE dados_prescricao(
    p_dt_emissao DATE,
    p_dt_expiracao DATE,
    p_id_consulta NUMBER,
    p_observacoes_gerais VARCHAR
)
IS
    v_id_consulta NUMBER := 0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    SELECT id_consulta INTO v_id_consulta FROM T_CLYVO_CONSULTA
        WHERE id_consulta = p_id_consulta;

    INSERT INTO T_CLYVO_PRESCRICAO(
        dt_emissao,
        dt_expiracao,
        id_consulta,
        observacoes_gerais
    )
    VALUES (
        p_dt_emissao,
        p_dt_expiracao,
        p_id_consulta,
        p_observacoes_gerais
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_prescricao',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
         WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_prescricao',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line('Id consulta não encontrado');
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_prescricao',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_prescricao;

-- Medicamento

CREATE OR REPLACE PROCEDURE dados_medicamento(
    p_id_prescricao NUMBER,
    p_nm_medicamento VARCHAR,
    p_dosagem_medicamento VARCHAR,
    p_frequencia VARCHAR,
    p_qtd_dias NUMBER
)
IS
    v_id_prescricao NUMBER :=0;
    v_codigo_erro VARCHAR(50);
    v_mensagem_erro VARCHAR(400);
BEGIN 
    SELECT id_prescricao INTO v_id_prescricao FROM T_CLYVO_PRESCRICAO
        WHERE id_prescricao = p_id_prescricao;
        
    INSERT INTO T_CLYVO_MEDICAMENTO(
        id_prescricao,
        nm_medicamento,
        dosagem_medicamento,
        frequencia,
        qtd_dias 
    )
    VALUES (
        p_id_prescricao,
        p_nm_medicamento,
        p_dosagem_medicamento,
        p_frequencia,
        p_qtd_dias
    );
    EXCEPTION
        WHEN VALUE_ERROR THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_medicamento',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
        WHEN NO_DATA_FOUND THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_medicamento',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line('Id prescricao não encontrado');
        WHEN OTHERS THEN
            v_codigo_erro := TO_CHAR(SQLCODE);
            v_mensagem_erro := SUBSTR(SQLERRM, 1, 400);
            INSERT INTO LOGS(
                nm_procedure,
                nm_usuario,
                dt_ocorrencia,
                codigo_erro,
                mensagem_erro 
            )VALUES (
                'dados_medicamento',
                USER,
                SYSDATE,
                v_codigo_erro, 
                v_mensagem_erro
            );
            dbms_output.put_line(v_mensagem_erro);
END dados_medicamento;

-- Inserir dados

--Vet

-- Veterinários disponíveis para teste: Ana | Antonio | Maria | Carlos | Paula
BEGIN 
    dados_vet('Ana', '17315657009', '54321-V', 'anaMaria@gmail.com', '54321');
    dados_vet('Antonio', '45678912311', '68090-JD', 'Antonio@gmail.com', '12580');
    dados_vet('Maria', '90654912311', '68090-SP', 'Maria@gmail.com', '8702');
    dados_vet('Carlos', '32165498700', '77010-RJ', 'Carlos@gmail.com', '9988');
    dados_vet('Paula', '65432198711', '55020-MG', 'Paula@gmail.com', '7766');
    COMMIT;
END;
/

--Clínica
BEGIN 
    dados_clinica('1111111111111', 'Saude animal');
    dados_clinica('222222222222', 'Animal love');
    dados_clinica('2345078912', 'Cuidado animal'); 
    COMMIT;
END;
/

-- Endereço da clínica
-- Clínicas disponíveis: Saude animal(1-SP), Animal love(2-SP/Guarulhos), Cuidado animal(3-RJ)
BEGIN 
    dados_endereco_clinica('Brasil', 'São Paulo', 'São Paulo', 'Lapa', 'R.dom Jose, 200', '200', 'Bloco A', '14253078', 1);
    dados_endereco_clinica('Brasil', 'São Paulo', 'Guarulhos', 'Centro', 'R. ipês, 510', '399', 'Casa', '14253079', 2);
    dados_endereco_clinica('Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Ipanema', 'Ipanema, 1000', '421', 'bloco A', '01310100', 3);
    COMMIT;
END;
/
    
-- Vet clínica
-- Associações: Ana(1)->Saude animal(1), Antonio(2)->Animal love(2),
--              Maria(3)->Cuidado animal(3), Carlos(4)->Saude animal(1), Paula(5)->Animal love(2)
BEGIN 
    dados_vet_clinica(1, 1);
    dados_vet_clinica(2, 2);
    dados_vet_clinica(3, 3);
    dados_vet_clinica(4, 1);
    dados_vet_clinica(5, 2);
    COMMIT;
END;
/

-- Responsável
BEGIN 
    dados_responsavel('45812579024', 'Jaci', '1134567890');
    dados_responsavel('54823687074', 'Felipe', '11987456123');
    dados_responsavel('12345678900', 'Alice', '11912345678');
    COMMIT;
END;
/

-- Endereço do responsável
BEGIN
    dados_endereco_responsavel('Brasil', 'São Paulo', 'São Paulo', 'Lapa', 'Dom jose', '123', '399', '01310200', 1);
    dados_endereco_responsavel('Brasil', 'São Paulo', 'Guarulhos', 'Vila Augusta', 'Costa leste', '456', '499', '02540450', 2);
    dados_endereco_responsavel('Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Botafogo', 'Av. das Flores', 'Rua são antonio', 'Bloco B', '01310100', 3);
    COMMIT;
END;
/

-- Animal
BEGIN
    dados_animal(NULL, '5482', 'Arthur', TO_DATE('2024-04-20', 'YYYY-MM-DD'), 60.5, 'cachorro', 'golden retriever', 1);
    dados_animal(NULL, NULL, 'Fofucho', TO_DATE('2020-08-10', 'YYYY-MM-DD'), 30, 'felino', 'Laranja', 1);
    dados_animal('54842785', '1230', 'Mimosa', TO_DATE('2025-02-19', 'YYYY-MM-DD'), 400, 'vaca', 'Angus', 2);
    dados_animal(NULL, NULL, 'Amber', TO_DATE('2019-04-10', 'YYYY-MM-DD'), 20.7, 'felino', 'vira-lata', 3);
    dados_animal('12442546', '13250', 'Hercules', TO_DATE('2022-03-20', 'YYYY-MM-DD'), 25, 'felino', 'vira-lata', 1);
    COMMIT;
END;
/

-- Endereço do animal
-- Todos os 5 animais possuem endereço cadastrado
BEGIN 
    dados_endereco_animal('Brasil', 'São Paulo', 'São Paulo', 'Lapa', 'Dom jose', '123', '399', '01310200', 1);
    dados_endereco_animal('Brasil', 'São Paulo', 'Presidente Prudente', 'Rancharia', 'rua dom santos', '789', '200', '01310222', 2);
    dados_endereco_animal('Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Botafogo', 'Av. das Flores', 'Rua são antonio', 'Bloco B', '01310100', 3);
    dados_endereco_animal('Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Ipanema', 'Rua Visc. Piraja', '110', 'Apto 201', '22410003', 4);
    dados_endereco_animal('Brasil', 'São Paulo', 'São Paulo', 'Moema', 'Av. Ibirapuera', '550', 'Casa', '04029000', 5);
    COMMIT;
END;
/

-- Carteira Vacinal
-- Todos os 5 animais possuem vacinas cadastradas
BEGIN
    dados_carteiravacinal('raiva', NULL, TO_DATE('2025-02-18','YYYY-MM-DD'), 'EFETUADA', 1);
    dados_carteiravacinal('Brucelose', TO_DATE('2026-11-24', 'YYYY-MM-DD'), TO_DATE('2025-08-30', 'YYYY-MM-DD'), 'PENDENTE', 2);
    dados_carteiravacinal('raiva', TO_DATE('2026-04-20', 'YYYY-MM-DD'), TO_DATE('2025-02-18', 'YYYY-MM-DD'), 'EFETUADA', 3);
    dados_carteiravacinal('V8', TO_DATE('2026-09-10', 'YYYY-MM-DD'), TO_DATE('2025-09-10', 'YYYY-MM-DD'), 'EFETUADA', 4);
    dados_carteiravacinal('Gripe felina', TO_DATE('2026-03-20', 'YYYY-MM-DD'), TO_DATE('2025-03-20', 'YYYY-MM-DD'), 'EFETUADA', 5);
    COMMIT;
END;
/

-- Consulta
-- Todos os 5 vets e todos os 5 animais possuem consultas cadastradas:
--   Arthur(1): consultas 1,2    | Fofucho(2): consulta 7
--   Mimosa(3): consultas 4,5,6 | Amber(4): consulta 8
--   Hercules(5): consultas 3,9 | (+consultas 10,11 para Carlos/Paula)
-- Veterinários: Ana(1), Antonio(2), Maria(3), Carlos(4), Paula(5)
BEGIN  
    dados_consulta('O paciente está com uma frequência grande de dor de coluna', 'passada', TO_DATE('2026-05-13', 'YYYY-MM-DD'), 2, 1);
    dados_consulta('O paciente está com sobrepeso', 'passada', TO_DATE('2026-05-13', 'YYYY-MM-DD'), 1, 1);
    dados_consulta('O paciente está com sobrepeso', 'execução', TO_DATE('2026-10-13', 'YYYY-MM-DD'), 2, 5);
    dados_consulta('O paciente está com frequência alta de vômitos', 'passada', TO_DATE('2026-05-04','YYYY-MM-DD'), 1, 3);
    dados_consulta('O paciente está com frequência alta de vômitos', 'passada', TO_DATE('2026-05-04','YYYY-MM-DD'), 3, 3);
    dados_consulta('O paciente está com a pata machucada', 'passada', TO_DATE('2026-05-04','YYYY-MM-DD'), 3, 3);
    dados_consulta('O paciente apresentou tosse persistente', 'passada', TO_DATE('2026-04-10','YYYY-MM-DD'), 2, 2);
    dados_consulta('O paciente está com dermatite', 'futura', TO_DATE('2026-07-15','YYYY-MM-DD'), 1, 4);
    dados_consulta('O paciente está com perda de apetite', 'passada', TO_DATE('2026-03-05','YYYY-MM-DD'), 4, 5);
    dados_consulta('O paciente está com conjuntivite', 'passada', TO_DATE('2026-04-22','YYYY-MM-DD'), 5, 2);
    dados_consulta('O paciente necessita de check-up geral', 'futura', TO_DATE('2026-08-01','YYYY-MM-DD'), 4, 3);
    COMMIT;
END;
/

-- Prescrição
-- Todas as 11 consultas possuem prescrição cadastrada
BEGIN 
    dados_prescricao(TO_DATE('2026-06-13','YYYY-MM-DD'), TO_DATE('2026-08-20','YYYY-MM-DD'), 1, 'Não correr muito rápido');
    dados_prescricao(TO_DATE('2026-10-22', 'YYYY-MM-DD'), TO_DATE('2026-12-01', 'YYYY-MM-DD'), 2, 'Sem observações');
    dados_prescricao(TO_DATE('2026-05-05', 'YYYY-MM-DD'), TO_DATE('2026-07-02', 'YYYY-MM-DD'), 3, 'Exame do estômago');
    dados_prescricao(TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_DATE('2026-07-10', 'YYYY-MM-DD'), 4, 'Hidratação reforçada');
    dados_prescricao(TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_DATE('2026-06-10', 'YYYY-MM-DD'), 5, 'Repouso e dieta leve');
    dados_prescricao(TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_DATE('2026-06-30', 'YYYY-MM-DD'), 6, 'Curativo e anti-inflamatório');
    dados_prescricao(TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-05-15', 'YYYY-MM-DD'), 7, 'Antibiótico por 10 dias');
    dados_prescricao(TO_DATE('2026-07-15', 'YYYY-MM-DD'), TO_DATE('2026-09-15', 'YYYY-MM-DD'), 8, 'Pomada dermatológica');
    dados_prescricao(TO_DATE('2026-03-10', 'YYYY-MM-DD'), TO_DATE('2026-04-10', 'YYYY-MM-DD'), 9, 'Estimular alimentação');
    dados_prescricao(TO_DATE('2026-04-25', 'YYYY-MM-DD'), TO_DATE('2026-05-25', 'YYYY-MM-DD'), 10, 'Colírio 2x ao dia');
    dados_prescricao(TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-10-01', 'YYYY-MM-DD'), 11, 'Exames preventivos');
    COMMIT;
END;
/

-- Medicamento
-- Todas as 11 prescrições possuem medicamento cadastrado
BEGIN
    dados_medicamento(1, 'Meloxicam', '0,5mg/kg', '1x ao dia', 10);
    dados_medicamento(2, 'Ração light', '300g', '2x ao dia', 30);
    dados_medicamento(3, 'Omeprazol', '1mg/kg', '1x ao dia', 14);
    dados_medicamento(4, 'Metoclopramida', '0,5mg/kg', '3x ao dia', 7);
    dados_medicamento(5, 'Dipirona', '25mg/kg', '2x ao dia', 5);
    dados_medicamento(6, 'Amoxicilina', '20mg/kg', '2x ao dia', 7);
    dados_medicamento(7, 'Doxiciclina', '5mg/kg', '1x ao dia', 10);
    dados_medicamento(8, 'Betametasona', '0,1mg/kg', '1x ao dia', 15);
    dados_medicamento(9, 'Mirtazapina', '1,5mg/kg', '1x ao dia', 14);
    dados_medicamento(10, 'Tobramicina', '1 gota', '3x ao dia', 7);
    dados_medicamento(11, 'Ivermectina', '0,2mg/kg', '1x ao dia', 1);
    COMMIT;
END;
/

--  Criar dois blocos anônimos para mostrar os dados inseridos, com pelo menos 3 consultas de junções (Joins) utilizando 
-- agrupamento (GROUP BY) e ordenação (ORDER BY).

-- Ver as consultas que cada veterinário possui
-- ================================================================
-- TESTE: Veterinários disponíveis: Ana | Antonio | Maria
-- ================================================================
DECLARE 
    buscar     VARCHAR(20) := '&nomeVeterinario';
    v_contador NUMBER := 0;
    CURSOR c_vet 
        IS SELECT 
            c.historico_consulta, c.st_consulta, c.dt_consulta, a.nm_animal, a.especie_animal,
            COUNT(c.id_consulta) AS consulta 
        FROM 
            T_CLYVO_CONSULTA c
        INNER JOIN
            T_CLYVO_ANIMAL a ON c.id_animal = a.id_animal
        INNER JOIN 
            T_CLYVO_VET v ON v.id_vet = c.id_vet
        WHERE
            v.nm_vet = buscar
        GROUP BY 
            v.nm_vet, c.historico_consulta, c.st_consulta, c.dt_consulta, a.nm_animal, a.especie_animal
        ORDER BY 
            a.nm_animal;
BEGIN
    dbms_output.put_line('Histórico de consultas de '||buscar);
    FOR v_exibe in c_vet LOOP
        v_contador := v_contador + 1;
        dbms_output.put_line('----------------------------------------------------------------------------');
        dbms_output.put_line('Paciente: '||v_exibe.nm_animal);
        dbms_output.put_line('Espécie: '||v_exibe.especie_animal);
        dbms_output.put_line('Data da consulta: '||v_exibe.dt_consulta);
        dbms_output.put_line('Status: '||v_exibe.st_consulta);
        dbms_output.put_line('Informação da consulta: '||v_exibe.historico_consulta);
    END LOOP;
    IF v_contador = 0 THEN
        dbms_output.put_line('Nenhuma consulta encontrada para o veterinário: '||buscar);
        dbms_output.put_line('Veterinários disponíveis: Ana | Antonio | Maria');
    END IF;
END;
/


-- Listagem do animal e informações sobre o tutor e carteira de vacinação
-- ================================================================
-- TESTE: Animais disponíveis: Arthur | Fofucho | Mimosa | Amber | Hercules
-- ================================================================
DECLARE 
    buscar     VARCHAR(20) := '&nomeAnimal';
    v_contador NUMBER := 0;
    CURSOR c_animal
        IS SELECT 
            a.rg_animal, a.nr_microchip_animal, a.nm_animal, a.dt_nascimento_animal, a.peso_animal, a.especie_animal, a.raca_animal, r.nm_responsavel,
            c.nm_vacina, c.dt_vacinacao_prevista, c.dt_vacinacao_efetuada, c.st_vacinacao, e_a.pais, e_a.estado, e_a.cidade, e_a.bairro,
            COUNT(a.id_animal) AS valor_vacina 
        FROM 
            T_CLYVO_ANIMAL a
        INNER JOIN
            T_CLYVO_CARTEIRAVACINAL c ON a.id_animal = c.id_animal
        INNER JOIN 
            T_CLYVO_RESPONSAVEL r ON a.id_responsavel = r.id_responsavel
        INNER JOIN
            T_CLYVO_ENDERECO_ANIMAL e_a ON e_a.id_animal = a.id_animal
        WHERE
            a.nm_animal = buscar
        GROUP BY 
            a.rg_animal, a.nr_microchip_animal,  a.nm_animal, a.dt_nascimento_animal, a.peso_animal, a.especie_animal, a.raca_animal, r.nm_responsavel,
            c.nm_vacina, c.dt_vacinacao_prevista, c.dt_vacinacao_efetuada, c.st_vacinacao, e_a.pais, e_a.estado, e_a.cidade, e_a.bairro
        ORDER BY 
            a.nm_animal;
BEGIN
    dbms_output.put_line('Informações de '||buscar);
    FOR v_exibe IN c_animal LOOP
        v_contador := v_contador + 1;
        dbms_output.put_line('----------------------------------------------------------------------------');
        dbms_output.put_line('Informações de '||v_exibe.nm_animal);
        dbms_output.put_line('      Nome do paciente: '||v_exibe.nm_animal);
        dbms_output.put_line('      Responsável: '||v_exibe.nm_responsavel);
        dbms_output.put_line('      Data de nascimento: '||v_exibe.dt_nascimento_animal);
        dbms_output.put_line('      Espécie: '||v_exibe.especie_animal);
        dbms_output.put_line('      Raça: '||v_exibe.raca_animal);
        dbms_output.put_line('Dados do animal: ');
        dbms_output.put_line('      RG animal: '||v_exibe.rg_animal);
        dbms_output.put_line('      Microchip: '||v_exibe.nr_microchip_animal);
        dbms_output.put_line('Carteira Vacinal: ');
        dbms_output.put_line('      Nome da vacina: '||v_exibe.nm_vacina);
        dbms_output.put_line('      Data prevista: '||v_exibe.dt_vacinacao_prevista);
        dbms_output.put_line('      Data efetuada: '||v_exibe.dt_vacinacao_efetuada);
        dbms_output.put_line('      Status da vacina: '||v_exibe.st_vacinacao);
        dbms_output.put_line('Endereço do animal: ');
        dbms_output.put_line('      País: '||v_exibe.pais);
        dbms_output.put_line('      Estado: '||v_exibe.estado);
        dbms_output.put_line('      Cidade: '||v_exibe.cidade);
        dbms_output.put_line('      Bairro: '||v_exibe.bairro);
    END LOOP;
    IF v_contador = 0 THEN
        dbms_output.put_line('Nenhum dado encontrado para o animal: '||buscar);
        dbms_output.put_line('Animais disponíveis: Arthur | Fofucho | Mimosa | Amber | Hercules');
    END IF;
    dbms_output.put_line('----------------------------------------------------------------------------');
END;
/


-- Criar um bloco que deverá ler os dados de uma tabela e, na mesma linha, mostrar o valor de uma coluna da linha atual, o valor 
-- dessa mesma coluna na linha anterior e o valor dessa mesma coluna na próxima linha. Caso a linha anterior ou a próxima linha não
-- existir, apresentar a palavra "Vazio". O relatório deve ter, pelo menos, cinco linhas de dados. A tabela e a coluna a ser exibida fica a
-- cargo do grupo.
-- ================================================================
-- Exibe os 5 veterinários com suas consultas (linha anterior/atual/próxima)
-- ================================================================
DECLARE 
    CURSOR c_veterinario IS
        SELECT v.id_vet, 
                v.nm_vet,
                CASE
                    WHEN 
                        SUM(CASE WHEN c.st_consulta='passada' THEN 1 ELSE 0 END)=0 THEN 'Vazio'
                    ELSE 
                        TO_CHAR(SUM(CASE WHEN c.st_consulta='passada' THEN 1 ELSE 0 END)) 
                    END AS v_consulta_realizada,
                CASE
                    WHEN 
                        SUM(CASE WHEN c.st_consulta='futura' THEN 1 ELSE 0 END)=0 THEN 'Vazio'
                    ELSE
                        TO_CHAR(SUM(CASE WHEN c.st_consulta='futura' THEN 1 ELSE 0 END)) 
                    END AS v_consulta_presentes, 
                    
                CASE 
                    WHEN
                        MAX(CASE WHEN c.st_consulta ='passada' THEN a.nm_animal END) IS NULL THEN 'Vazio'
                    ELSE
                        MAX(CASE WHEN c.st_consulta ='passada' THEN a.nm_animal END)
                    END AS ultima_passada, 
                    
                CASE
                    WHEN
                        MAX(CASE WHEN c.st_consulta ='execução' THEN a.nm_animal END) IS NULL THEN 'Vazio'
                    ELSE
                        MAX(CASE WHEN c.st_consulta ='execução' THEN a.nm_animal END)
                    END AS con_execucao,
                    
                CASE
                    WHEN
                        MAX(CASE WHEN c.st_consulta='futura' THEN a.nm_animal END) IS NULL THEN 'Vazio'
                    ELSE
                        MAX(CASE WHEN c.st_consulta='futura' THEN a.nm_animal END)
                    END AS con_futura,
                    
                MAX(c.dt_consulta) as dt_consulta
        FROM 
            T_CLYVO_VET v
        INNER JOIN 
            T_CLYVO_CONSULTA c ON v.id_vet = c.id_vet
        INNER JOIN
            T_CLYVO_ANIMAL a ON c.id_animal =  a.id_animal
        GROUP BY v.id_vet, v.nm_vet
        ORDER BY v.id_vet;
BEGIN

    dbms_output.put_line(
        RPAD('ID_VET',8) ||
        RPAD('NM_VET',15) ||
        RPAD('CON_REALIZADA',17) ||
        RPAD('CON_PENDENTE',16) ||
        RPAD('CON_ANTERIOR',18) ||
        RPAD('CON_ATUAL',18) ||
        RPAD('CON_PROXIMA',18) ||
        RPAD('PRÓXIMO DIA DA CONSULTA',12)
    );
    FOR v_vet IN c_veterinario LOOP
        dbms_output.put_line(
            RPAD(v_vet.id_vet,8) ||
            RPAD(v_vet.nm_vet,15) ||
            RPAD(v_vet.v_consulta_realizada,17) ||
            RPAD(v_vet.v_consulta_presentes,16) ||
            RPAD(v_vet.ultima_passada,18) ||
            RPAD(v_vet.con_execucao,18) ||
            RPAD(v_vet.con_futura,18) ||
            RPAD(TO_CHAR(v_vet.dt_consulta, 'DD/MM/YYYY'),12)
        );
    END LOOP;
END;
/


-- ================================================================
-- Relatório de animais: dados numéricos sumarizados por espécie
-- Lista todos os animais, com peso médio, maior e menor peso
-- agrupados por espécie (critério de agrupamento)
-- ================================================================
DECLARE
    v_totalAnimais  NUMBER := 0;
    v_existe        NUMBER := 0;

    CURSOR c_animais IS
        SELECT
            especie_animal,
            COUNT(id_animal)            AS qtd_animais,
            ROUND(AVG(peso_animal), 2)  AS peso_medio,
            MAX(peso_animal)            AS maior_peso,
            MIN(peso_animal)            AS menor_peso
        FROM T_CLYVO_ANIMAL
        GROUP BY especie_animal
        ORDER BY especie_animal;

    TYPE t_animais IS TABLE OF c_animais%ROWTYPE;
    v_animais t_animais;

BEGIN
    -- Verifica se há animais cadastrados
    SELECT COUNT(*) INTO v_existe FROM T_CLYVO_ANIMAL;

    dbms_output.put_line('Relatório de animais por espécie:');
    dbms_output.put_line(
        RPAD('ESPÉCIE',20)      ||
        RPAD('QTD',8)           ||
        RPAD('PESO MÉDIO',14)   ||
        RPAD('MAIOR PESO',14)   ||
        RPAD('MENOR PESO',14)
    );
    dbms_output.put_line(RPAD('-', 70, '-'));

    IF v_existe = 0 THEN
        dbms_output.put_line('Nenhum animal cadastrado no sistema.');
    ELSE
        OPEN c_animais;
        FETCH c_animais BULK COLLECT INTO v_animais;
        CLOSE c_animais;

        FOR i IN 1..v_animais.COUNT LOOP
            v_totalAnimais := v_totalAnimais + v_animais(i).qtd_animais;
            dbms_output.put_line(
                RPAD(v_animais(i).especie_animal, 20)                 ||
                RPAD(v_animais(i).qtd_animais, 8)                     ||
                RPAD(TO_CHAR(v_animais(i).peso_medio,  '999.99'), 14) ||
                RPAD(TO_CHAR(v_animais(i).maior_peso,  '999.99'), 14) ||
                RPAD(TO_CHAR(v_animais(i).menor_peso,  '999.99'), 14)
            );
        END LOOP;

        dbms_output.put_line(RPAD('-', 70, '-'));
        dbms_output.put_line('Total geral de animais cadastrados: ' || v_totalAnimais);
    END IF;
END;
/


-- Quantas consultas cada clínica fez

DECLARE
v_consultaRealizada NUMBER := 0;
totalGeral NUMBER := 0;
CURSOR c_clinica IS
    SELECT 
        c.nm_clinica,
        COUNT(vc.id_vet) AS total_vet,
        ec.estado,
        SUM(CASE
            WHEN 
                con.st_consulta ='passada' THEN 1 ELSE 0
            END) AS v_realizada
    FROM T_CLYVO_CLINICA c
    INNER JOIN  T_CLYVO_VET_CLINICA vc ON c.id_clinica = vc.id_clinica
    INNER JOIN T_CLYVO_CONSULTA con ON vc.id_vet = con.id_vet
    INNER JOIN T_CLYVO_ENDERECO_CLINICA ec ON  c.id_clinica = ec.id_clinica
    GROUP BY c.nm_clinica, ec.estado
    ORDER BY ec.estado, c.nm_clinica;

    TYPE t_clinica IS TABLE OF c_clinica%ROWTYPE;
    v_clinica t_clinica;
    
BEGIN
    OPEN c_clinica ;
    FETCH c_clinica BULK COLLECT INTO v_clinica;
    CLOSE c_clinica;
    dbms_output.put_line('Relatório sobre as clínicas');
    IF v_clinica.COUNT = 0 THEN
        dbms_output.put_line('Nenhum dado encontrado: clínicas sem consultas cadastradas.');
    ELSE
        dbms_output.put_line(
            RPAD('NM CLÍNICA ',20) ||
            RPAD('Quantidade de VET ',25) ||
            RPAD(' CONSULTAS REALIZADAS',20)
        );
        -- Para diferenciar os estados
        FOR i IN 1..v_clinica.COUNT LOOP
        
            totalGeral := totalGeral + v_clinica(i).v_realizada;
            
            IF i > 1 AND v_clinica(i).estado != v_clinica(i-1).estado THEN
                dbms_output.put_line('Sub-Total de '||v_clinica(i-1).estado||': '||v_consultaRealizada);
                v_consultaRealizada := v_clinica(i).v_realizada;
            ELSE
                v_consultaRealizada := v_consultaRealizada + v_clinica(i).v_realizada;
            END IF;
                dbms_output.put_line(
                    RPAD(v_clinica(i).nm_clinica,20) ||
                    RPAD(v_clinica(i).total_vet,25) ||
                    RPAD(v_clinica(i).v_realizada,20)
                );
        END LOOP;
        dbms_output.put_line('Sub-Total de '||v_clinica(v_clinica.COUNT).estado||': '||v_consultaRealizada);
        dbms_output.put_line('Total Geral: '||totalGeral);
    END IF;
END;
/

-- Quantidade de consultas realizadas por veterinário em cada clínica
DECLARE
v_consultaRealizada NUMBER := 0;
totalGeral NUMBER := 0;
pacienteFrequente VARCHAR(20) :='';
n NUMBER :=0;

CURSOR c_consulta IS
    SELECT 
        a.nm_animal,
        MAX(c.nm_clinica) AS nm_clinica,
        MAX(v.nm_vet) AS nm_vet,
        SUM(CASE
            WHEN 
                con.st_consulta ='passada' THEN 1 ELSE 0
            END) AS v_realizada
    FROM T_CLYVO_CONSULTA con
    INNER JOIN T_CLYVO_ANIMAL a ON con.id_animal = a.id_animal
    INNER JOIN T_CLYVO_VET v ON con.id_vet = v.id_vet
    INNER JOIN  T_CLYVO_VET_CLINICA vc ON v.id_vet = vc.id_vet
    INNER JOIN T_CLYVO_CLINICA c ON vc.id_clinica = c.id_clinica
    GROUP BY a.nm_animal
    ORDER BY a.nm_animal;

    TYPE t_consulta IS TABLE OF c_consulta%ROWTYPE;
    v_consulta t_consulta;
    
BEGIN
    OPEN c_consulta ;
    FETCH c_consulta BULK COLLECT INTO v_consulta;
    CLOSE c_consulta;
    dbms_output.put_line('Relatório sobre frequência dos animais');
    IF v_consulta.COUNT = 0 THEN
        dbms_output.put_line('Nenhum dado encontrado: sem consultas cadastradas.');
    ELSE
        dbms_output.put_line(
            RPAD('Nome do paciente ',20) ||
            RPAD('Veterinário ',18) ||
            RPAD('Clínica responsável ',20) ||
            RPAD('Frequência',20)
        );
        
        FOR i IN 1..v_consulta.COUNT LOOP
        
            totalGeral := totalGeral + v_consulta(i).v_realizada;
            v_consultaRealizada := v_consultaRealizada + v_consulta(i).v_realizada;

            dbms_output.put_line(
                    RPAD(v_consulta(i).nm_animal,20) ||
                    RPAD(v_consulta(i).nm_vet,18) ||
                    RPAD(v_consulta(i).nm_clinica,20) ||
                    RPAD(v_consulta(i).v_realizada,20)
                );
            
            IF v_consulta(i).v_realizada > n THEN
                pacienteFrequente := v_consulta(i).nm_animal;
                n := v_consulta(i).v_realizada;
            END IF;
            
        END LOOP;
        
        -- Ver qual foi o paciente mais frequente
        dbms_output.put_line('Paciente mais frequente: '||pacienteFrequente);
        dbms_output.put_line('Total Geral: '||totalGeral);
    END IF;
END;
/

-- Tutor e animal: verificação de endereço em comum
DECLARE
    petTutor number := 0;
    petSozinho     number := 0;
    v_contador     number := 0;
    CURSOR c_animal IS
    SELECT 
        a.nm_animal,
        r.nm_tutor,
        ena.bairro as an_bairro,
        env.bairro as res_bairro
    FROM T_CLYVO_TUTOR r
    INNER JOIN T_CLYVO_ANIMAL a ON r.id_tutor = a.id_tutor
    INNER JOIN T_CLYVO_ENDERECO_TUTOR env ON r.id_tutor = env.id_tutor
    INNER JOIN  T_CLYVO_ENDERECO_ANIMAL ena ON a.id_animal = ena.id_animal
    ORDER BY a.nm_animal;

BEGIN
    dbms_output.put_line('Relatório sobre moradia do Responsável e do animal: ');
    dbms_output.put_line(
        RPAD('NM animal ',20) ||
        RPAD('Responsável ',25) ||
        RPAD('Mesma localização',20)
    );
    FOR v_animal IN c_animal LOOP
        v_contador := v_contador + 1;
        IF v_animal.an_bairro = v_animal.res_bairro THEN
            dbms_output.put_line(
                RPAD(v_animal.nm_animal,20) ||
                RPAD(v_animal.nm_tutor,25) ||
                RPAD('SIM',20)
            );
            petResponsavel := petResponsavel+1;
        ELSE
            dbms_output.put_line(
                RPAD(v_animal.nm_animal,20) ||
                RPAD(v_animal.nm_tutor,25) ||
                RPAD('Não',20)
            );
            petSozinho := petSozinho+1;
        END IF;
    END LOOP;
    IF v_contador = 0 THEN
        dbms_output.put_line('Nenhum dado encontrado: sem animais ou endereços cadastrados.');
    ELSE
        dbms_output.put_line('Animais que vivem com o responsável: '||petTutor);
        dbms_output.put_line('Animais que vivem em lugar diferente do responsável: '||petSozinho);
    END IF;
END;    
/

-- ================================================================
-- TESTE DO LOG: forçando erros propositais para popular a tabela LOGS
-- ================================================================
BEGIN
    -- Erro 1: CPF duplicado (Ana já existe)
    dados_vet('Ana Teste', '17315657009', '99999-X', 'ana2@gmail.com', '1234');
    
    -- Erro 2: CNPJ duplicado (clínica já existe)
    dados_clinica('1111111111111', 'Clinica Duplicada');
    
    -- Erro 3: id_clinica inexistente
    dados_endereco_clinica('Brasil', 'SP', 'SP', 'Centro', 'Rua A', '1', 'Casa', '00000000', 99);
    
    -- Erro 4: CPF de responsável duplicado
    dados_responsavel('45812579024', 'Jaci Duplicado', '11999999999');
    
    COMMIT;
END;
/

-- Log
-- Relatório de ocorrências
-- (Este bloco só exibe dados se houver erros gerados pelas procedures)
DECLARE
    valorSeparado NUMBER := 0;
    totalGeral NUMBER := 0;
    CURSOR c_log
        IS SELECT 
            id_log, nm_procedure, nm_usuario, dt_ocorrencia, codigo_erro, mensagem_erro
        FROM LOGS
        ORDER BY nm_procedure;
        
    TYPE t_log IS TABLE OF c_log%ROWTYPE;
    v_log t_log;
BEGIN
    OPEN c_log;
    FETCH c_log BULK COLLECT INTO v_log;
    CLOSE c_log;
    dbms_output.put_line('Relatório de ocorrências: ');
    IF v_log.COUNT = 0 THEN
        dbms_output.put_line('Nenhuma ocorrência registrada no log.');
        dbms_output.put_line('(O log é preenchido automaticamente quando ocorre algum erro nas procedures)');
    ELSE
        dbms_output.put_line(
            RPAD('NM Procedure',20) ||
            RPAD('Data Ocorrência',25) ||
            RPAD('Código',15) ||
            RPAD('MENSAGEM',30)
        );
        FOR i IN 1..v_log.COUNT LOOP
        
            totalGeral := totalGeral +1;
            valorSeparado := valorSeparado+1;
            
            IF i > 1 AND v_log(i).nm_procedure != v_log(i-1).nm_procedure THEN
                dbms_output.put_line('Sub-Total de '||v_log(i-1).nm_procedure||': '||(valorSeparado-1));
                valorSeparado := 1;
            END IF;
            dbms_output.put_line(
            RPAD(v_log(i).nm_procedure,20) ||
            RPAD(TO_CHAR(v_log(i).dt_ocorrencia, 'DD/MM/YYYY'),20) ||
            RPAD(v_log(i).codigo_erro,15) ||
            RPAD(v_log(i).mensagem_erro,30)
            );  
        END LOOP;
        dbms_output.put_line('Sub-Total de '||v_log(v_log.COUNT).nm_procedure||': '||valorSeparado);
        dbms_output.put_line('Total de ocorrências: '||totalGeral);
    END IF;
END;
/




