-- ===================================================================
-- Script de criação das tabelas CORE (CP4) + dados de exemplo
-- ===================================================================

CREATE TABLE T_CLYVO_TUTOR(
  id_tutor number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  cpf_tutor VARCHAR(20) UNIQUE NOT NULL,
  nm_tutor VARCHAR(20) NOT NULL,
  nr_telefone_tutor VARCHAR(13) NOT NULL
);

CREATE TABLE T_CLYVO_ANIMAL(
  id_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  rg_animal VARCHAR(20),
  nr_microchip_animal VARCHAR(20),
  nm_animal VARCHAR(20) NOT NULL,
  dt_nascimento_animal DATE NOT NULL,
  peso_animal number(5,2) NOT NULL,
  especie_animal VARCHAR(20) NOT NULL,
  raca_animal VARCHAR(20) NOT NULL,
  id_tutor number(2) NOT NULL,
  CONSTRAINT fk_an_tutor FOREIGN KEY (id_tutor) REFERENCES T_CLYVO_TUTOR(id_tutor)
);

CREATE TABLE T_CLYVO_CARTEIRAVACINAL(
  id_carteiravacinal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  nm_vacina VARCHAR(20) NOT NULL,
  dt_vacinacao_prevista DATE,
  dt_vacinacao_efetuada DATE NOT NULL,
  st_vacinacao VARCHAR(20) CHECK (st_vacinacao IN ('EFETUADA','PENDENTE','ATRASADA','CANCELADA')),
  id_animal number(2) NOT NULL,
  CONSTRAINT fk_an_carteiravacinal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

-- ===================================================================
-- Dados de exemplo (requisito: pelo menos 2 linhas significativas)
-- ===================================================================

INSERT INTO T_CLYVO_TUTOR (cpf_tutor, nm_tutor, nr_telefone_tutor)
VALUES ('123.456.789-00', 'Maria Silva', '11987654321');

INSERT INTO T_CLYVO_TUTOR (cpf_tutor, nm_tutor, nr_telefone_tutor)
VALUES ('987.654.321-00', 'Joao Souza', '11912345678');

INSERT INTO T_CLYVO_ANIMAL (nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_tutor)
VALUES ('Rex', DATE '2020-05-10', 22.50, 'Cachorro', 'Labrador', 1);

INSERT INTO T_CLYVO_ANIMAL (nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_tutor)
VALUES ('Mia', DATE '2021-08-22', 4.20, 'Gato', 'Siames', 2);

INSERT INTO T_CLYVO_CARTEIRAVACINAL (nm_vacina, dt_vacinacao_prevista, dt_vacinacao_efetuada, st_vacinacao, id_animal)
VALUES ('V10', DATE '2024-01-15', DATE '2024-01-15', 'EFETUADA', 1);

INSERT INTO T_CLYVO_CARTEIRAVACINAL (nm_vacina, dt_vacinacao_prevista, dt_vacinacao_efetuada, st_vacinacao, id_animal)
VALUES ('Antirrabica', DATE '2024-02-20', DATE '2024-02-20', 'EFETUADA', 2);

COMMIT;
